import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir } from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const deployTarget = process.env.STELLA_DEPLOY_TARGET;

const deployFiles = ["main.js", "manifest.json", "styles.css"];

const deployPlugin = {
  name: "deploy-to-vault",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0 || !deployTarget) return;
      try {
        await mkdir(deployTarget, { recursive: true });
        await Promise.all(
          deployFiles.map((f) =>
            copyFile(f, path.join(deployTarget, f)).catch((err) => {
              if (err.code !== "ENOENT") throw err;
            }),
          ),
        );
        console.log(`[deploy] copied → ${deployTarget}`);
      } catch (err) {
        console.error(`[deploy] failed: ${err.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [deployPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
